//! Outbound mail submission shapes.

use core::fmt;

use engine_core::ids::{MessageIdHeader, ProviderKey};
use engine_core::mail::EmailAddress;
use serde::{Deserialize, Serialize};

/// A mail message to send.
///
/// The `message_id` is generated by the caller **before** submission (the Write
/// Contract: a stable `Message-ID` precedes the send), so the sent copy can be
/// reconciled by `Message-ID` when it later syncs back (`store-and-sync.md`).
/// The body always carries a plain-text fallback and may add an HTML alternative
/// plus inline or regular attachments. Serializable so a caller can store it as a
/// durable outbox `PendingOp` payload before sending.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Draft {
    /// The pre-generated `Message-ID` header value (no angle brackets).
    pub message_id: MessageIdHeader,
    /// The sender address.
    pub from: EmailAddress,
    /// The recipient addresses.
    pub to: Vec<EmailAddress>,
    /// The `Cc` ("carbon copy") recipients — visible to every recipient. Empty for
    /// none. Defaulted so a payload serialized before Cc/Bcc support still deserializes.
    #[serde(default)]
    pub cc: Vec<EmailAddress>,
    /// The `Bcc` ("blind carbon copy") recipients. They are delivered to (added to the
    /// SMTP envelope) but, by convention, **never** written as a message header, so no
    /// other recipient can see them. Empty for none. Defaulted for back-compat like `cc`.
    #[serde(default)]
    pub bcc: Vec<EmailAddress>,
    /// The subject.
    pub subject: String,
    /// The plain-text body.
    pub text_body: String,
    /// The optional HTML alternative body.
    #[serde(default)]
    pub html_body: Option<String>,
    /// Inline and regular draft attachments.
    #[serde(default)]
    pub attachments: Vec<DraftAttachment>,
    /// The `Message-ID` this message replies to, if any — the RFC 5322 §3.6.4
    /// `In-Reply-To` value (the parent's `Message-ID`, no angle brackets). `None`
    /// for an original (non-reply) message. Defaulted so a payload serialized
    /// before threading support still deserializes.
    #[serde(default)]
    pub in_reply_to: Option<MessageIdHeader>,
    /// The RFC 5322 §3.6.4 `References` chain that threads this message with its
    /// original: the parent's `References` followed by the parent's own
    /// `Message-ID`, oldest first (each value with no angle brackets). Empty for an
    /// original (non-reply) message. Defaulted for back-compat like `in_reply_to`.
    #[serde(default)]
    pub references: Vec<MessageIdHeader>,
}

impl Draft {
    /// Assembles a draft to send.
    ///
    /// The threading linkage defaults to none; set it with the
    /// [`in_reply_to`](Draft::in_reply_to) builder for a reply or forward.
    #[must_use]
    pub fn new(
        message_id: MessageIdHeader,
        from: EmailAddress,
        to: Vec<EmailAddress>,
        subject: impl Into<String>,
        text_body: impl Into<String>,
    ) -> Self {
        Self {
            message_id,
            from,
            to,
            cc: Vec::new(),
            bcc: Vec::new(),
            subject: subject.into(),
            text_body: text_body.into(),
            html_body: None,
            attachments: Vec::new(),
            in_reply_to: None,
            references: Vec::new(),
        }
    }

    /// Sets the `Cc` recipients (visible to every recipient).
    #[must_use]
    pub fn with_cc(mut self, cc: Vec<EmailAddress>) -> Self {
        self.cc = cc;
        self
    }

    /// Sets the `Bcc` recipients — delivered via the SMTP envelope but never emitted as
    /// a header, so they stay hidden from every other recipient.
    #[must_use]
    pub fn with_bcc(mut self, bcc: Vec<EmailAddress>) -> Self {
        self.bcc = bcc;
        self
    }

    /// Sets the threading linkage for a reply or forward: the `parent` message's
    /// `Message-ID` (the RFC 5322 §3.6.4 `In-Reply-To`) and the full `references`
    /// chain (the parent's `References` plus its own `Message-ID`, oldest first).
    /// The SMTP assembler emits both so the sent message threads with its original.
    #[must_use]
    pub fn in_reply_to(
        mut self,
        parent: MessageIdHeader,
        references: Vec<MessageIdHeader>,
    ) -> Self {
        self.in_reply_to = Some(parent);
        self.references = references;
        self
    }

    /// Adds an HTML alternative body.
    #[must_use]
    pub fn with_html_body(mut self, html_body: impl Into<String>) -> Self {
        self.html_body = Some(html_body.into());
        self
    }

    /// Clears the HTML alternative body.
    #[must_use]
    pub fn without_html_body(mut self) -> Self {
        self.html_body = None;
        self
    }

    /// Adds an inline or regular attachment.
    #[must_use]
    pub fn with_attachment(mut self, attachment: DraftAttachment) -> Self {
        self.attachments.push(attachment);
        self
    }
}

/// A validated `Content-ID` header value without surrounding angle brackets.
///
/// The type keeps inline-image references distinct from arbitrary strings and
/// prevents the characters that would break the header boundary.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct ContentIdHeader(Box<str>);

impl ContentIdHeader {
    /// Builds a content id value without surrounding angle brackets.
    ///
    /// # Errors
    ///
    /// Returns [`ContentIdError`] when the value is empty or contains a character
    /// that cannot be safely placed inside a `Content-ID` header.
    pub fn new(value: impl Into<String>) -> Result<Self, ContentIdError> {
        let value = value.into();
        if value.is_empty() {
            return Err(ContentIdError::Empty);
        }
        if value
            .bytes()
            .any(|b| matches!(b, b'\r' | b'\n' | b'\0' | b'<' | b'>'))
        {
            return Err(ContentIdError::ForbiddenCharacter);
        }
        Ok(Self(value.into_boxed_str()))
    }

    /// Returns the header value without surrounding angle brackets.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ContentIdHeader {
    type Error = ContentIdError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<ContentIdHeader> for String {
    fn from(value: ContentIdHeader) -> Self {
        value.0.into()
    }
}

impl fmt::Display for ContentIdHeader {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Why a `Content-ID` header value was rejected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContentIdError {
    /// The value was empty.
    Empty,
    /// The value contained CR, LF, NUL, `<`, or `>`.
    ForbiddenCharacter,
}

impl fmt::Display for ContentIdError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => f.write_str("content id must not be empty"),
            Self::ForbiddenCharacter => {
                f.write_str("content id contains a forbidden character (CR, LF, NUL, '<', or '>')")
            }
        }
    }
}

impl std::error::Error for ContentIdError {}

/// Whether a draft attachment is a regular attachment or an inline related part.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum DraftAttachmentDisposition {
    /// The part is referenced from the HTML body with a `cid:` URL.
    Inline {
        /// The `Content-ID` value without surrounding angle brackets.
        content_id: ContentIdHeader,
    },
    /// The part should be presented as a regular downloadable attachment.
    Attachment,
}

/// A draft attachment to include in the outbound MIME message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DraftAttachment {
    /// The display file name.
    pub file_name: String,
    /// The media type, for example `image/png` or `application/pdf`.
    pub media_type: String,
    /// The attachment bytes.
    pub content: Vec<u8>,
    /// How the part is related to the body.
    pub disposition: DraftAttachmentDisposition,
}

impl DraftAttachment {
    /// Builds an inline attachment referenced by a `cid:` URL in the HTML body.
    #[must_use]
    pub fn inline(
        file_name: impl Into<String>,
        media_type: impl Into<String>,
        content_id: ContentIdHeader,
        content: Vec<u8>,
    ) -> Self {
        Self {
            file_name: file_name.into(),
            media_type: media_type.into(),
            content,
            disposition: DraftAttachmentDisposition::Inline { content_id },
        }
    }

    /// Builds a regular downloadable attachment.
    #[must_use]
    pub fn attachment(
        file_name: impl Into<String>,
        media_type: impl Into<String>,
        content: Vec<u8>,
    ) -> Self {
        Self {
            file_name: file_name.into(),
            media_type: media_type.into(),
            content,
            disposition: DraftAttachmentDisposition::Attachment,
        }
    }

    /// Returns the inline content id, if this is an inline attachment.
    #[must_use]
    pub fn content_id(&self) -> Option<&ContentIdHeader> {
        match &self.disposition {
            DraftAttachmentDisposition::Inline { content_id } => Some(content_id),
            DraftAttachmentDisposition::Attachment => None,
        }
    }

    /// Whether this part is an inline related attachment.
    #[must_use]
    pub fn is_inline(&self) -> bool {
        matches!(self.disposition, DraftAttachmentDisposition::Inline { .. })
    }
}

/// The result of a successful submission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubmissionReceipt {
    /// The provider key of the sent message (filed in Sent), for the outbox to
    /// record as the op's resolved key.
    pub email_key: ProviderKey,
    /// The `Message-ID` that was sent, echoed for sync-time reconciliation.
    pub message_id: MessageIdHeader,
}

impl SubmissionReceipt {
    /// Records a submission result.
    #[must_use]
    pub fn new(email_key: ProviderKey, message_id: MessageIdHeader) -> Self {
        Self {
            email_key,
            message_id,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mid(value: &str) -> MessageIdHeader {
        MessageIdHeader::new(value).unwrap()
    }

    fn draft() -> Draft {
        Draft::new(
            mid("reply@host"),
            EmailAddress::new("alice@test.local"),
            vec![EmailAddress::new("bob@test.local")],
            "Re: hi",
            "thanks",
        )
    }

    #[test]
    fn new_defaults_the_threading_linkage_to_none() {
        let draft = draft();
        assert_eq!(draft.in_reply_to, None);
        assert!(draft.references.is_empty());
    }

    #[test]
    fn in_reply_to_builder_sets_parent_and_references() {
        let draft = draft().in_reply_to(
            mid("parent@host"),
            vec![mid("root@host"), mid("parent@host")],
        );
        assert_eq!(draft.in_reply_to, Some(mid("parent@host")));
        assert_eq!(draft.references, vec![mid("root@host"), mid("parent@host")]);
    }

    #[test]
    fn new_defaults_cc_and_bcc_to_empty() {
        let draft = draft();
        assert!(draft.cc.is_empty());
        assert!(draft.bcc.is_empty());
    }

    #[test]
    fn cc_and_bcc_builders_set_recipients() {
        let draft = draft()
            .with_cc(vec![EmailAddress::new("carol@test.local")])
            .with_bcc(vec![EmailAddress::new("dave@test.local")]);
        assert_eq!(draft.cc, vec![EmailAddress::new("carol@test.local")]);
        assert_eq!(draft.bcc, vec![EmailAddress::new("dave@test.local")]);
    }

    #[test]
    fn cc_and_bcc_round_trip_through_serde() {
        let draft = draft()
            .with_cc(vec![EmailAddress::new("carol@test.local")])
            .with_bcc(vec![EmailAddress::new("dave@test.local")]);
        let json = serde_json::to_string(&draft).unwrap();
        let restored: Draft = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.cc, draft.cc);
        assert_eq!(restored.bcc, draft.bcc);
    }

    #[test]
    fn a_payload_without_cc_or_bcc_still_deserializes() {
        // A durable outbox payload serialized before Cc/Bcc support omits the new fields;
        // `#[serde(default)]` keeps it loadable with empty recipient lists.
        let json = r#"{
            "message_id": "old@host",
            "from": {"email": "alice@test.local"},
            "to": [{"email": "bob@test.local"}],
            "subject": "hi",
            "text_body": "body"
        }"#;
        let restored: Draft = serde_json::from_str(json).unwrap();
        assert!(restored.cc.is_empty());
        assert!(restored.bcc.is_empty());
    }

    #[test]
    fn serde_round_trip_preserves_the_threading_fields() {
        let draft = draft().in_reply_to(
            mid("parent@host"),
            vec![mid("root@host"), mid("parent@host")],
        );
        let json = serde_json::to_string(&draft).unwrap();
        let restored: Draft = serde_json::from_str(&json).unwrap();
        assert_eq!(restored, draft);
        assert_eq!(restored.in_reply_to, Some(mid("parent@host")));
        assert_eq!(
            restored.references,
            vec![mid("root@host"), mid("parent@host")]
        );
    }

    #[test]
    fn a_payload_without_the_threading_fields_still_deserializes() {
        // A durable outbox payload serialized before threading support omits the new
        // fields; `#[serde(default)]` keeps it loadable as a non-reply draft.
        let json = r#"{
            "message_id": "old@host",
            "from": {"email": "alice@test.local"},
            "to": [{"email": "bob@test.local"}],
            "subject": "hi",
            "text_body": "body"
        }"#;
        let restored: Draft = serde_json::from_str(json).unwrap();
        assert_eq!(restored.in_reply_to, None);
        assert!(restored.references.is_empty());
    }

    #[test]
    fn a_payload_without_rich_body_fields_still_deserializes() {
        // A durable outbox payload serialized before rich-body support omits the new
        // fields; defaults keep it loadable as a plain-text draft.
        let json = r#"{
            "message_id": "old@host",
            "from": {"email": "alice@test.local"},
            "to": [{"email": "bob@test.local"}],
            "subject": "hi",
            "text_body": "body"
        }"#;
        let restored: Draft = serde_json::from_str(json).unwrap();
        assert_eq!(restored.html_body, None);
        assert!(restored.attachments.is_empty());
    }

    #[test]
    fn rich_draft_builders_set_html_and_attachments() {
        let inline = DraftAttachment::inline(
            "chart.png",
            "image/png",
            ContentIdHeader::new("chart.1@test.local").unwrap(),
            vec![1, 2, 3],
        );
        let file = DraftAttachment::attachment("report.pdf", "application/pdf", vec![4, 5]);

        let draft = draft()
            .with_html_body("<p>thanks</p>")
            .with_attachment(inline.clone())
            .with_attachment(file.clone());

        assert_eq!(draft.html_body.as_deref(), Some("<p>thanks</p>"));
        assert_eq!(draft.attachments, vec![inline, file]);
    }
}
