//! Outbound mail submission shapes.

use engine_core::ids::{MessageIdHeader, ProviderKey};
use engine_core::mail::EmailAddress;
use serde::{Deserialize, Serialize};

/// A mail message to send.
///
/// The `message_id` is generated by the caller **before** submission (the Write
/// Contract: a stable `Message-ID` precedes the send), so the sent copy can be
/// reconciled by `Message-ID` when it later syncs back (`store-and-sync.md`).
/// The body is plain text; richer bodies are a later concern. Serializable so a
/// caller can store it as a durable outbox `PendingOp` payload before sending.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Draft {
    /// The pre-generated `Message-ID` header value (no angle brackets).
    pub message_id: MessageIdHeader,
    /// The sender address.
    pub from: EmailAddress,
    /// The recipient addresses.
    pub to: Vec<EmailAddress>,
    /// The subject.
    pub subject: String,
    /// The plain-text body.
    pub text_body: String,
}

impl Draft {
    /// Assembles a draft to send.
    #[must_use]
    pub fn new(
        message_id: MessageIdHeader,
        from: EmailAddress,
        to: Vec<EmailAddress>,
        subject: impl Into<String>,
        text_body: impl Into<String>,
    ) -> Self {
        Self {
            message_id,
            from,
            to,
            subject: subject.into(),
            text_body: text_body.into(),
        }
    }
}

/// The result of a successful submission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubmissionReceipt {
    /// The provider key of the sent message (filed in Sent), for the outbox to
    /// record as the op's resolved key.
    pub email_key: ProviderKey,
    /// The `Message-ID` that was sent, echoed for sync-time reconciliation.
    pub message_id: MessageIdHeader,
}

impl SubmissionReceipt {
    /// Records a submission result.
    #[must_use]
    pub fn new(email_key: ProviderKey, message_id: MessageIdHeader) -> Self {
        Self {
            email_key,
            message_id,
        }
    }
}
